controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    legs_controller:
      type: joint_trajectory_controller/JointTrajectoryController

legs_controller:
  ros__parameters:
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    joints:
      - front_left_hip_joint
      - front_left_thigh_joint
      - front_left_calf_joint
      - front_right_hip_joint
      - front_right_thigh_joint
      - front_right_calf_joint
      - rear_left_hip_joint
      - rear_left_thigh_joint
      - rear_left_calf_joint
      - rear_right_hip_joint
      - rear_right_thigh_joint
      - rear_right_calf_joint
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    allow_nonzero_velocity_at_trajectory_end: true
